export const searchdata =[{
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdOKoyjbcAGun8H6Rb57WpPSRJSe4F7MnahQ&usqp=CAU",
    location:"Private room in center of New York",
    title:"Stay at this spacious Edwardian House",
    description:"1 guest · 1 bedroom · 1 bed · 1.5 shared bthrooms · Wifi · Kitchen · Free parking · Washing Machine",
    star:4.73,
    price:"£30 / night",
    total:"£117 total",
},
{
    img:"https://www.expatkings.com/wp-content/uploads/2018/10/Airbnb-rental-tips.-Hostmaker-1-620x349.jpg",
    location:"Private room in center of London",
    title:"Independant luxury studio apartment",
    description:"2 guest · 3 bedroom · 1 bed · 1.5 shared bthrooms · Wifi · Kitchen",
    star:4.3,
    price:"£40 / night",
    total:"£157 total",
},
{
    img:"https://www.smartertravel.com/uploads/2017/07/Untitled-design-8.jpg",
    title:"London Studio Apartments",
    description:"4 guest · 4 bedroom · 4 bed · 2 bathrooms · Free parking · Washing Machine",
    star:3.8,
    price:"£35 / night",
    total:"£207 total" ,
},
{
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNlgxJabRYeuiQzV2qsH34xbb20OdtwKv10Q&usqp=CAU",
    location:"Private room in center of London",
    title:"30 mins to Oxford Street, Excel London",
    description:"1 guest · 1 bedroom · 1 bed · 1.5 shared bthrooms · Wifi · Kitchen · Free parking · Washing Machine",
    star:4.1,
    price:"£55 / night",
    total:"£320 total",
},
{
    img:"https://media.cntraveler.com/photos/5a8f258bd363c34048b35aac/master/w_2250,h_1500,c_limit/airbnb-plus-london.jpg",
    location:"Private room in center of London",
    title:"Spacious Peaceful Modern Bedroom",
    description:"3 guest · 1 bedroom · 1 bed · 1.5 shared bthrooms · Wifi · Free parking · Dry Cleaning",
    star:5.0,
    price:"£60 / night",
    total:"£450 total",
},
{
    img:"https://static.trip101.com/paragraph_media/pictures/001/676/061/large/969ae4bb-efd1-4fb9-a4e3-5cb3316dd3c9.jpg?1562227937",
    location:"Private room in center of London",
    title:"The Blue Room In London",
    description:"2 guest · 1 bedroom · 1 bed · 1.5 shared bthrooms · Wifi · Washing Machine",
    star:4.23,
    price:"£65 / night",
    total:"£480 total",
},
{
    img:"https://image.insider.com/585029a0dd0895bc548b4b8b?width:750&format:jpeg&auto:webp",
    location:"Private room in center of London",
    title:"5 Star Luxury Apartment",
    description:"3 guest · 1 bedroom · 1 bed · 1.5 shared bthrooms · Wifi · Kitchen · Free parking · Washing Machine",
    star:3.85,
    price:"£90 / night",
    total:"£650 total",
}
]